version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: empleados_db
      POSTGRES_USER: empleado_user
      POSTGRES_PASSWORD: empleado_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: empleados_db
      DB_USER: empleado_user
      DB_PASSWORD: empleado_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data: